export const UrlPath = {
  Root: "/",
  MyPage: "/job/MyPage",
  JobSearch: "/job/JobSearch",
  ShareArea: "/job/ShareArea",
  LogSearch: "/job/LogSearch",
  JobCreate: "/job/JobCreate",
  Tool: "/job/Tool",
  OAUsers: "/OA/Users",
  OAOrders: "/OA/Orders",
  UserManage: "/manage/User",
  UserCreate: "/manage/User/new",
  UserEdit: "/manage/User/:user_cd",
  CenterManage: "/manage/Center",
  CenterCreate: "/manage/Center/new",
  CenterEdit: "/manage/Center/:center_cd",
  ManageRole: "/manage/Role",
  Information: "/manage/Information",
  System: "/manage/System",
  UserSetting: "/manage/UserSetting",
  Batch: "/manage/Batch",
  MyPageEdit: "/user/MyPageEdit",
  UserProfile: "/user/Profile",
  SS: "/ss",
  Development: "/Development",
} as const;

export type UrlPath = (typeof UrlPath)[keyof typeof UrlPath];